import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import Appbar from "@/components/Appbar";
import { Toaster } from "sonner";

const merriweather = Merriweather({ subsets: ["latin"] , weight:"300" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} text-[#003C2F] bg-[#F8F9FA]`}>
        <Appbar />
        <Toaster richColors position="top-right" />
        {children}
      </body>
    </html>
  );
}
